version: "3.9"
services:
  web:
    build: .
    port:
      - 8090:8000
    command: ["./wait-for-it.sh", "mysql:3306", "--", "./target/debug/truffle_rs"]
  mysql:
    image: "mysql:latest"
    restart: always
    environment:
      MYSQL_DATABASE: "test"
      MYSQL_ROOT_PASSWORD: mysql
    ports:
      - 3306:3306
    security_opt:
      - seccomp:unconfined
